package WebService.webServiceClient.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.List;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 */
@WebService(name = "ManagerServiceImp", targetNamespace = "http://service.baizhi.com/")
@XmlSeeAlso({ObjectFactory.class})
public interface ManagerServiceImp {


    /**
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "delete", targetNamespace = "http://service.baizhi.com/", className = "com.baizhi.service.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://service.baizhi.com/", className = "com.baizhi.service.DeleteResponse")
    @Action(input = "http://service.baizhi.com/ManagerServiceImp/deleteRequest", output = "http://service.baizhi.com/ManagerServiceImp/deleteResponse")
    public void delete(@WebParam(name = "arg0", targetNamespace = "") Integer arg0);

    /**
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "insert", targetNamespace = "http://service.baizhi.com/", className = "com.baizhi.service.Insert")
    @ResponseWrapper(localName = "insertResponse", targetNamespace = "http://service.baizhi.com/", className = "com.baizhi.service.InsertResponse")
    @Action(input = "http://service.baizhi.com/ManagerServiceImp/insertRequest", output = "http://service.baizhi.com/ManagerServiceImp/insertResponse")
    public void insert(@WebParam(name = "arg0", targetNamespace = "") Manager arg0);

    /**
     * @param arg1
     * @param arg0
     * @return returns com.baizhi.service.Manager
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "query", targetNamespace = "http://service.baizhi.com/", className = "com.baizhi.service.Query")
    @ResponseWrapper(localName = "queryResponse", targetNamespace = "http://service.baizhi.com/", className = "com.baizhi.service.QueryResponse")
    @Action(input = "http://service.baizhi.com/ManagerServiceImp/queryRequest", output = "http://service.baizhi.com/ManagerServiceImp/queryResponse")
    public Manager query(@WebParam(name = "arg0", targetNamespace = "") String arg0, @WebParam(name = "arg1", targetNamespace = "") String arg1);

    /**
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "update", targetNamespace = "http://service.baizhi.com/", className = "com.baizhi.service.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://service.baizhi.com/", className = "com.baizhi.service.UpdateResponse")
    @Action(input = "http://service.baizhi.com/ManagerServiceImp/updateRequest", output = "http://service.baizhi.com/ManagerServiceImp/updateResponse")
    public void update(@WebParam(name = "arg0", targetNamespace = "") Manager arg0);

    /**
     * @param arg0
     * @return returns com.baizhi.service.Manager
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryByid", targetNamespace = "http://service.baizhi.com/", className = "com.baizhi.service.QueryByid")
    @ResponseWrapper(localName = "queryByidResponse", targetNamespace = "http://service.baizhi.com/", className = "com.baizhi.service.QueryByidResponse")
    @Action(input = "http://service.baizhi.com/ManagerServiceImp/queryByidRequest", output = "http://service.baizhi.com/ManagerServiceImp/queryByidResponse")
    public Manager queryByid(@WebParam(name = "arg0", targetNamespace = "") Integer arg0);

    /**
     * @param arg0
     * @return returns java.util.List<com.baizhi.service.Manager>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryByname", targetNamespace = "http://service.baizhi.com/", className = "com.baizhi.service.QueryByname")
    @ResponseWrapper(localName = "queryBynameResponse", targetNamespace = "http://service.baizhi.com/", className = "com.baizhi.service.QueryBynameResponse")
    @Action(input = "http://service.baizhi.com/ManagerServiceImp/queryBynameRequest", output = "http://service.baizhi.com/ManagerServiceImp/queryBynameResponse")
    public List<Manager> queryByname(@WebParam(name = "arg0", targetNamespace = "") String arg0);

    /**
     * @return returns java.util.List<com.baizhi.service.Manager>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryAll", targetNamespace = "http://service.baizhi.com/", className = "com.baizhi.service.QueryAll")
    @ResponseWrapper(localName = "queryAllResponse", targetNamespace = "http://service.baizhi.com/", className = "com.baizhi.service.QueryAllResponse")
    @Action(input = "http://service.baizhi.com/ManagerServiceImp/queryAllRequest", output = "http://service.baizhi.com/ManagerServiceImp/queryAllResponse")
    public List<Manager> queryAll();

    /**
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deletes", targetNamespace = "http://service.baizhi.com/", className = "com.baizhi.service.Deletes")
    @ResponseWrapper(localName = "deletesResponse", targetNamespace = "http://service.baizhi.com/", className = "com.baizhi.service.DeletesResponse")
    @Action(input = "http://service.baizhi.com/ManagerServiceImp/deletesRequest", output = "http://service.baizhi.com/ManagerServiceImp/deletesResponse")
    public void deletes(@WebParam(name = "arg0", targetNamespace = "") List<Integer> arg0);

    /**
     * @param arg1
     * @param arg0
     * @return returns java.util.List<com.baizhi.service.Manager>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryBypage", targetNamespace = "http://service.baizhi.com/", className = "com.baizhi.service.QueryBypage")
    @ResponseWrapper(localName = "queryBypageResponse", targetNamespace = "http://service.baizhi.com/", className = "com.baizhi.service.QueryBypageResponse")
    @Action(input = "http://service.baizhi.com/ManagerServiceImp/queryBypageRequest", output = "http://service.baizhi.com/ManagerServiceImp/queryBypageResponse")
    public List<Manager> queryBypage(@WebParam(name = "arg0", targetNamespace = "") Integer arg0, @WebParam(name = "arg1", targetNamespace = "") Integer arg1);

}
