package WebService.webServiceClient.service;

import com.baizhi.service.ManagerServiceImp;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 */
@WebServiceClient(name = "ManagerServiceImpService", targetNamespace = "http://service.baizhi.com/", wsdlLocation = "http://localhost:8888/IDEAmanager?wsdl")
public class ManagerServiceImpService extends Service {

    private final static URL MANAGERSERVICEIMPSERVICE_WSDL_LOCATION;
    private final static WebServiceException MANAGERSERVICEIMPSERVICE_EXCEPTION;
    private final static QName MANAGERSERVICEIMPSERVICE_QNAME = new QName("http://service.baizhi.com/", "ManagerServiceImpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/IDEAmanager?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MANAGERSERVICEIMPSERVICE_WSDL_LOCATION = url;
        MANAGERSERVICEIMPSERVICE_EXCEPTION = e;
    }

    public ManagerServiceImpService() {
        super(__getWsdlLocation(), MANAGERSERVICEIMPSERVICE_QNAME);
    }

    public ManagerServiceImpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MANAGERSERVICEIMPSERVICE_QNAME, features);
    }

    public ManagerServiceImpService(URL wsdlLocation) {
        super(wsdlLocation, MANAGERSERVICEIMPSERVICE_QNAME);
    }

    public ManagerServiceImpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MANAGERSERVICEIMPSERVICE_QNAME, features);
    }

    public ManagerServiceImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ManagerServiceImpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns ManagerServiceImp
     */
    @WebEndpoint(name = "ManagerServiceImpPort")
    public com.baizhi.service.ManagerServiceImp getManagerServiceImpPort() {
        return super.getPort(new QName("http://service.baizhi.com/", "ManagerServiceImpPort"), com.baizhi.service.ManagerServiceImp.class);
    }

    /**
     * @param features A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns ManagerServiceImp
     */
    @WebEndpoint(name = "ManagerServiceImpPort")
    public com.baizhi.service.ManagerServiceImp getManagerServiceImpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.baizhi.com/", "ManagerServiceImpPort"), ManagerServiceImp.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MANAGERSERVICEIMPSERVICE_EXCEPTION != null) {
            throw MANAGERSERVICEIMPSERVICE_EXCEPTION;
        }
        return MANAGERSERVICEIMPSERVICE_WSDL_LOCATION;
    }

}
